### ISSUE TITLE
Any change on making Handy Notes also available on Wago?

### ISSUE THREAD

**Issue by Vakke** [Nevcairiel/HandyNotes#2]
Any change on making Handy Notes also available on Wago?

Curseforge's new API is trying to kill 3rd party addons managers and as I use Windows Insider I cannot download or use Curseforge. This also applies to Linux users.

Wago for example is supporting both platforms it would help us keep on using the addon!

**Comment by Nevcairiel** [comment]
No, wago is of no interest. HandyNotes is available on CurseForge, WoWInterface as well as right here on GitHub.
